# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Label PRs based on branch name
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: TimonVS/pr-labeler-action@v4.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr-labeler.yml
